http-port: 23940 #port to run http proxy on
api-port: 23941 #api port
threads: 100 #thread number.
source: https://raw.githubusercontent.com/reny311/proxyTop/master/sub/sub_merge_yaml.yml
outfile: check.yaml
test-url: https://gstatic.com/generate_204
timeout: 3000 #timeout in miliseconds
