name: clash
on: 
  schedule:
    - cron: '*/32 0-14 * * *'
    - cron: '*/51 14-23 * * *'
  workflow_dispatch:

jobs:
  me-job:
    name: sub_merge
    runs-on : ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: 安装依赖
      run: |
        pip install -r ./utils/requirements.txt
    - name: 执行任务
      run: |
        wget -O subconverter.tar.gz https://github.com/tindy2013/subconverter/releases/latest/download/subconverter_linux64.tar.gz
        tar -zxvf subconverter.tar.gz -C ./
        chmod +x ./subconverter/subconverter && nohup ./subconverter/subconverter >./subconverter.log 2>&1 &
        python ./utils/list_merge.py
      
    - name: 提交更改
      run: |                 
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull origin master
        git add ./sub
        git add README.md
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S')合并节点"
    - name: 推送更改
      uses:  ad-m/github-push-action@master
      with:
        branch: master
  cc-job: #input./utils/clashcheck/config.yaml
    name: ClashCheck
    needs: me-job
    # runs-on: self-hosted #python git pip和镜像
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: init
      run: | 
         git config pull.rebase false
         git config --local user.name "GitHub Actions"
         git config --local user.email "actions@github.com"
         # pip config set local.index-url https://pypi.tuna.tsinghua.edu.cn/simple
    - name: requirements.txt
      run: pip install -r ./utils/clashcheck/requirements.txt
    - name: main.py
      run: cd ./utils/clashcheck/ && python main.py && python main.py && python main.py
    - run: ./.github/update-repo.sh || true   #output./utils/clashcheck/check.yaml

  rm-job: #input./utils/clashcheck/check.yaml
    name: rm
    needs: cc-job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: git init
      run: | 
         git config pull.rebase false
         git config --local user.name "GitHub Actions"
         git config --local user.email "actions@github.com"
    - name: subconverter #input./utils/clashcheck/check.yaml
      run: cd ./utils/subconverter/ && ./subconverter -g --artifact "rm"
    - name: rm
      run: | #input./utils/subconverter/rm1
         mv ./utils/subconverter/rm1 ./utils/rm/rm1
         cd ./utils/rm/
         #input./utils/rm/rm1
         base64 -d rm1 > rm2 #output./utils/rm/rm2
         npm install
         #input./utils/rm/package-lock.json
         #input./utils/rm/rm2
         npm start
         #output./utils/rm/url
    - name: url & https & check
      run: | #input./utils/rm/url ./url ./.github/url.sh ./1 ./2 ./3
         rm ./utils/rm/rm1 ./utils/rm/rm2
         #input./utils/rm/url
         mv ./utils/rm/url ./url #output./url
         #input./url
         base64 ./url > ./utils/pool/check -w 0 #output./utils/pool/check
         #input./.github/url.sh
         ./.github/url.sh > ./1 #output./1
         #input./url
         cp ./url ./2 #output./2
         #input./1 ./2
         cat 1 2 > 3 && rm 1 2 #output./3
         #input./3
         base64 3 > https -w 0 && rm 3 #output./https ./url
    - run: ./.github/update-repo.sh || true   #output./url ./https ./utils/pool/check

  et-job: #input./utils/pool/check ./utils/pool/pool
    name: Encode & Translate
    needs: rm-job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Timezone
      run: |
            sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: git init
      run: | 
         git config pull.rebase false
         git config --local user.name "GitHub Actions"
         git config --local user.email "actions@github.com"
    - name: subconverter
      run: | #input./utils/pool/check ./utils/pool/pool ./utils/clashcheck/check.yaml
         sudo chmod +x ./utils/subconverter/subconverter && ./utils/subconverter/subconverter -g 
         sudo chmod +x ./long && sudo chmod +x ./Clash.yaml
         #output./utils/subconverter/long ./utils/subconverter/Clash.yaml ./utils/subconverter/pool.yaml ./utils/subconverter/rm1
         sudo mv ./utils/subconverter/long ./long || true
         sudo mv ./utils/subconverter/Clash.yaml ./Clash.yaml || true
         sudo rm ./utils/subconverter/pool.yaml ./utils/subconverter/rm1
    - run: ./.github/update-repo.sh || true   #output./long ./Clash.yaml
  sp-job:
    name: sp
    needs: et-job
    runs-on : ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: 加载缓存
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: 安装依赖
      run: |
        pip install -r ./utils/requirements.txt
    - name: speedtest
      run: |
        sudo sh ./utils/speedtest/speedtest.sh
        python ./utils/speedtest/output.py
        python ./utils/eternity_convert.py
    - name: commit
      run: |                 
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull origin master
        git add Eternity
        git add Eternity.yml
        git add README.md
        git add ./update/*
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S')筛选节点"
    - name: 推送更改
      uses:  ad-m/github-push-action@master
      with:
        # github_token: ${{ secrets.TOKEN }}
        branch: master
