name: Clash
on: 
  schedule:
    - cron: '*/32 0-14 * * *'
    - cron: '*/51 14-23 * * *'
  workflow_dispatch:

jobs:
  rm-job: #input./utils/clashcheck/check.yaml
    name: rm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Timezone
      run: |
            sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: git init
      run: | 
         git config pull.rebase false
         git config --local user.name "GitHub Actions"
         git config --local user.email "actions@github.com"
    - name: subconverter #input./utils/clashcheck/check.yaml
      run:   sudo chmod +x ./utils/subconverter/subconverter && cd ./utils/subconverter/ && ./subconverter -g --artifact "rm"
    - name: rm
      run: | #input./utils/subconverter/rm1
         chmod +x ./.github/update-repo.sh
         mv ./utils/subconverter/rm1 ./utils/rm/rm1
         sudo chmod +x ./utils/rm/location.js
         sudo chmod +x ./utils/rm/index.js
         cd ./utils/rm/
         #input./utils/rm/rm1
         base64 -d rm1 > rm2 #output./utils/rm/rm2
         sudo npm install
         #input./utils/rm/package-lock.json
         #input./utils/rm/rm2
         npm start
         #output./utils/rm/url
    - name: url & https & check
      run: | #input./utils/rm/url ./url ./.github/url.sh ./1 ./2 ./3
         sudo rm ./utils/rm/rm1 ./utils/rm/rm2
         #input./utils/rm/url
         sudo mv ./utils/rm/url ./url #output./url
         #input./url
         base64 ./url > ./utils/pool/check -w 0 #output./utils/pool/check
         #input./.github/url.sh
         sudo chmod +x ./.github/url.sh
         ./.github/url.sh > ./1 #output./1
         #input./url
         sudo cp ./url ./2 #output./2
         #input./1 ./2
         cat 1 2 > 3 && rm 1 2 #output./3
         #input./3
         base64 3 > https -w 0 && rm 3 #output./https
    - run: ./.github/update-repo.sh || true   #output./url ./https ./utils/pool/check

  et-job: #input./utils/pool/check ./utils/pool/pool
    name: Encode & Translate
    needs: rm-job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Timezone
      run: |
            sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: git init
      run: | 
         git config pull.rebase false
         git config --local user.name "GitHub Actions"
         git config --local user.email "actions@github.com"
    - name: subconverter
      run: | #input./utils/pool/check ./utils/pool/pool ./utils/clashcheck/check.yaml
         sudo chmod +x ./utils/subconverter/subconverter && ./utils/subconverter/subconverter -g 
         #output./utils/subconverter/long ./utils/subconverter/Clash.yaml ./utils/subconverter/pool.yaml ./utils/subconverter/rm1
         mv ./utils/subconverter/long ./long || true
         sudo mv ./utils/subconverter/Clash.yaml ./Clash.yaml || true
         sudo rm ./utils/subconverter/pool.yaml ./utils/subconverter/rm1
    - run: ./.github/update-repo.sh || true   #output./long ./Clash.yaml
